server:
  port: 8081

mybatis:
  mapper-locations:
  type-aliases-package: com.chuweizi.visualization.entity

#showSql
logging:
  level:
    com:
      chuweizi:
        script: DEBUG


security:
  basic:
    enabled=false:
